module.exports = (sequelize, type) => {
    return sequelize.define("empresas", {
        id: {
            type: type.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        nombre: type.STRING,
        nombre_comercial: type.STRING,
        direccion: type.STRING,
        ubigeo_id: type.INTEGER,
        ruc: type.STRING,
        user_id: type.INTEGER,
        telefono: type.STRING,
        celular: type.STRING,
        email: type.STRING,
        decimales: type.STRING,
        por_detraccion: type.INTEGER,
        igv: type.STRING,
        logo: type.STRING,
        certificado: type.STRING,
        certificado_clave: type.STRING,
        certificado_validate: type.STRING,
        usuario_sunat: type.STRING,
        usuario_sunat_clave: type.STRING,
        agente: type.STRING,
        por_percepcion: type.INTEGER,
        por_retencion: type.INTEGER,
        limite_detraccion: type.STRING,
        cuenta_detraccion: type.STRING,
        country_id: type.INTEGER,
        estatus: type.STRING,
        detalle: type.STRING,
        created_at: type.STRING,
        updated_at: type.STRING,
        smtp_mail_host: type.STRING,
        smtp_mail_port: type.INTEGER,
        smtp_mail_service: type.STRING,
        smtp_mail_auth_user: type.STRING,
        smtp_mail_auth_password: type.STRING,
    });
};
